load("@bazel_skylib//rules:build_test.bzl", "build_test")

build_test(
    name = "arm_linux_test",
    targets = ["//test/arm-linux:hex"],
)

build_test(
    name = "arm_none_test",
    targets = ["//test/arm-none:hex"],
)
