constraint_setting(
    name = "cpu",
)

constraint_value(
    name = "a53",
    constraint_setting = "cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "a72",
    constraint_setting = "cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "a76",
    constraint_setting = "cpu",
    visibility = ["//visibility:public"],
)
