load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "aspect_bazel_lib",
    sha256 = "d0203b032a26086729ade48c46bc6159fb4aa825d9a5bdf2d972449bcbefe967",
    strip_prefix = "bazel-lib-1.42.1",
    url = "https://github.com/aspect-build/bazel-lib/releases/download/v1.42.1/bazel-lib-v1.42.1.tar.gz",
)

load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies")

aspect_bazel_lib_dependencies()

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "rules_cc",
    commit = "4a62c693309887664cb733245d1c74f17a992942",
    remote = "https://github.com/bazelbuild/rules_cc",
)

local_repository(
    name = "toolchains_arm_gnu",
    path = "../../",
)

load("@toolchains_arm_gnu//:deps.bzl", "arm_none_eabi_deps", "arm_none_linux_gnueabihf_deps")

# Toolchain: arm-none-eabi
arm_none_eabi_deps()

register_toolchains("@arm_none_eabi//toolchain:all")

# Toolchain arm-none-linux-gnueabihf
arm_none_linux_gnueabihf_deps()

register_toolchains("@arm_none_linux_gnueabihf//toolchain:all")

# Custom toolchain
register_toolchains("//custom/toolchain:all")
