platform(
    name = "cortex_m4",
    constraint_values = [
        "@platforms//os:none",
        "//examples/custom/cpu:cortex_m4",
    ],
    visibility = ["//visibility:public"],
)

platform(
    name = "cortex_m3",
    constraint_values = [
        "@platforms//os:none",
        "//examples/custom/cpu:cortex_m3",
    ],
    visibility = ["//visibility:public"],
)
