constraint_setting(
    name = "arm_none_eabi_cpu",
)

constraint_value(
    name = "cortex_m3",
    constraint_setting = "arm_none_eabi_cpu",
    visibility = ["//visibility:public"],
)

constraint_value(
    name = "cortex_m4",
    constraint_setting = "arm_none_eabi_cpu",
    visibility = ["//visibility:public"],
)
