platform(
    name = "raspberry_pi_3",
    constraint_values = [
        "@platforms//os:none",
        "//cpu:a53",
    ],
    visibility = ["//visibility:public"],
)

platform(
    name = "raspberry_pi_4",
    constraint_values = [
        "@platforms//os:none",
        "//cpu:a72",
    ],
    visibility = ["//visibility:public"],
)

platform(
    name = "raspberry_pi_5",
    constraint_values = [
        "@platforms//os:none",
        "//cpu:a76",
    ],
    visibility = ["//visibility:public"],
)