constraint_setting(
    name = "internal_bootstrap_constraint",
)

constraint_value(
    name = "bootstrap",
    constraint_setting = "internal_bootstrap_constraint",
    visibility = ["//visibility:public"],
)
